spring:
  application:
    name: busgo-backend
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/busgo}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Let Hibernate auto-create tables for now
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    # Removed standard SMTP as it is blocked by Railway
    # Migrated to Brevo HTTP API
    
brevo:
  api-key: ${BREVO_API_KEY}

paystack:
  secret-key: "sk_test_62a08d998b7212ca20a9d354af63fe3c1986d363"

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # Sample 256-bit secret (32 bytes hex)
  expiration: 86400000 # 1 day in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.busgo.backend: DEBUG
    org.springframework.security: DEBUG
